### PR TITLE
Master -> Main Rename

### PR DESCRIPTION
**Pull request by dannylamb**
Part of https://github.com/Islandora/documentation/issues/1595

### CODE REVIEW

**Review by rosiel — APPROVED** [review]

**Comment by whikloj** [comment]
Just noting that a lot of these ansible-role PRs all were opened against `master` and so will either need to be redone against `main` or have `master` pushed to `main` again.

**Comment by rosiel** [comment]
Thanks @whikloj. While Danny's out, what do you suggest?

**Comment by whikloj** [comment]
I think it's probably easiest to just push `master` back on top of `main` and then delete the `master` branches so we don't make that mistake again.

**Comment by dannylamb** [comment]
done... and the master branch has been deleted

**Comment by dannylamb** [comment]
prolly gonna have to go through these one by one in Islandora-Devops.  Sry bout the mess folks

**Pull request merged**
