### PR TITLE
Add CI Testing

### PR DESCRIPTION
**Pull request by jonathangreen**
I've always liked how http://github.com/geerlingguy tests his ansible roles, so I added tests the same way here. I'm hoping this can be an example of how we can do it, then we can apply to all our roles. 

Ticket: 
https://github.com/Islandora-CLAW/CLAW/issues/794

### CODE REVIEW

**Comment by jonathangreen** [comment]
This tests: 
- Does a syntax lint
- Runs the playbook inside a docker container for appropriate OS
- Re-runs the playbook to make sure nothing changed 

This doesn't mean that the playbook actually properly installs whatever its supposed to install, just that it doesn't error out in the process of running the playbook. In practice though, I think it will be better then nothing.

**Comment by whikloj** [comment]
@jonathangreen 👍 nice work, this is exactly what we need for all these roles and for `claw-playbook` proper.

I'll hold here for 24 hours in case @dannylamb or @Natkeeran have anything to say. But otherwise I think we should add this to all the repos in `Islandora-Devops`.

**Review by dannylamb — APPROVED** [review]
Cool.  :+1: 

I'm going to make a personal copy of that gist you're pulling down just in case.  You never know.

**Comment by dannylamb** [comment]
Forked it out of paranoia: https://gist.github.com/dannylamb/c57a00786bf5f90883678ad3dc1a2183

**Pull request merged**
